language: node_js
node_js:
- "5.8"
addons:
  ssh_known_hosts: 45.79.201.206
before_install:
- openssl aes-256-cbc -K $encrypted_ea5d83bfe4fe_key -iv $encrypted_ea5d83bfe4fe_iv
  -in deploy-key.pem.enc -out deploy-key.pem -d
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: script
  script: deploy/deploy.sh
  skip_cleanup: true
  on:
    branch: develop
notifications:
  slack: bitovi:a6EZ5xpLzrpMgCYyvKwfkmN5
