language: node_js
node_js:
- '5.8'
addons:
  ssh_known_hosts: 
    - develop.bithub.com
    - staging.bithub.com
before_install:
- openssl aes-256-cbc -K $encrypted_34b14dba4b3c_key -iv $encrypted_34b14dba4b3c_iv
  -in deploy-key.pem.enc -out deploy-key.pem -d
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  - provider: script
    script: ./.travis/deploy-develop.sh
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: ./.travis/deploy-staging.sh
    skip_cleanup: true
    on:
      branch: staging
notifications:
  slack: bitovi:a6EZ5xpLzrpMgCYyvKwfkmN5
